import { StyleSheet } from 'react-native';
import { getCommonStyles } from '../../common/styles';
import { ThemeType } from '../../common/theme';

const getStyles = (colors: ThemeType) => StyleSheet.create({
  ...getCommonStyles(colors),

  container: { flex: 1, backgroundColor: colors.background },
  headerContainer: { paddingHorizontal: 20, paddingTop: 35, backgroundColor: colors.surface, paddingBottom: 10 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  headerTitle: { fontSize: 25, fontWeight: 'bold', color: colors.textPrimary, flex: 1 },
  addButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, position: 'relative' },
  searchIcon: { position: 'absolute', left: 15, zIndex: 1 },
  clearIcon: { position: 'absolute', right: 15, zIndex: 1 },
  searchInput: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 25,
    paddingLeft: 45,
    paddingRight: 45,
    height: 45,
    color: colors.textPrimary,
  },
  filtersScroll: { flexDirection: 'row' },
  filterChip: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 10,
  },
  filterChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  filterText: { color: colors.textSecondary, fontSize: 14, fontWeight: '600' },
  filterTextActive: { color: colors.white },
  listContainer: { flex: 1 },
  listContent: { padding: 20, paddingBottom: 100 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    marginBottom: 20,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  imageContainer: { height: 180, width: '100%', position: 'relative' },
  cardImage: { width: '100%', height: '100%' },
  categoryBadge: {
    position: 'absolute',
    top: 15,
    left: 15,
    backgroundColor: colors.overlay,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  categoryText: { color: colors.white, fontSize: 11, fontWeight: 'bold' },
  cardBody: { padding: 15, flexDirection: 'row', justifyContent: 'space-between'},
  cardText: { flexDirection: 'column', rowGap: 2, justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 5 },
  cardTitle: { fontSize: 16, fontWeight: 'bold', color: colors.textPrimary, flex: 1, marginRight: 10 },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 5,
    paddingVertical: 0,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ratingText: { fontSize: 14, fontWeight: 'bold', color: colors.warning, marginLeft: 5 },
  locationRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  locationInfo: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 12 },
  locationText: { fontSize: 13, color: colors.textSecondary, marginLeft: 4, flex: 1 },
  emptyStateContainer: { alignItems: 'center', justifyContent: 'center', marginTop: 50 },
  emptyStateText: { marginTop: 10, color: colors.textMuted, fontSize: 14, fontWeight: '500' },

  statusBadge: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
  },

});

export default getStyles;
