import { Platform, StyleSheet } from "react-native";
import { commonStyles } from "../../common/styles";

const styles = StyleSheet.create({
    ...commonStyles,

    container: {
        flex: 1,
        backgroundColor: '#F8F9FB',
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'android' ? 42 : 14,
        paddingBottom: 44,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 18,
        columnGap: 12,
    },
    headerTitle: {
        flex: 1,
        fontSize: 18,
        fontWeight: '700',
        color: '#003A70',
        textAlign: 'center',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        minHeight: 46,
        paddingVertical: 12,
        borderRadius: 14,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        columnGap: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: '#333',
        paddingVertical: 0,
    },
    filterScroll: {
        marginBottom: 14,
        flexGrow: 0,
    },
    filterChip: {
        paddingVertical: 9,
        paddingHorizontal: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    filterChipActive: {
        borderColor: '#006699',
        backgroundColor: '#E6F0FA',
    },
    filterChipText: {
        fontSize: 13,
        color: '#707B81',
        fontWeight: '500',
    },
    filterChipTextActive: {
        color: '#006699',
        fontWeight: '600',
    },
    sourceSwitch: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8EEF4',
        borderRadius: 14,
        padding: 4,
        marginBottom: 16,
    },
    sourceSwitchButton: {
        flex: 1,
        minHeight: 38,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        columnGap: 7,
    },
    sourceSwitchButtonActive: {
        backgroundColor: '#006699',
        shadowColor: '#003A70',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 7,
        elevation: 2,
    },
    sourceSwitchText: {
        color: '#64748B',
        fontSize: 13,
        fontWeight: '700',
    },
    sourceSwitchTextActive: {
        color: '#FFFFFF',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#003A70',
        marginLeft: 8,
    },
    card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 16,
        marginBottom: 12,
        columnGap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
    },
    cardImg: {
        width: 64,
        height: 64,
        borderRadius: 12,
        backgroundColor: '#E2E8F0',
    },
    cardImageWrap: {
        width: 64,
        height: 64,
        borderRadius: 12,
        position: 'relative',
    },
    cardDealBadge: {
        position: 'absolute',
        top: -6,
        right: -6,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#0F6C82',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    cardInfo: {
        flex: 1,
        minWidth: 0,
    },
    placeName: {
        fontSize: 15,
        fontWeight: '700',
        color: '#003A70',
        marginBottom: 6,
    },
    ratingRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        columnGap: 6,
    },
    ratingText: {
        flex: 1,
        fontSize: 12,
        color: '#707B81',
        lineHeight: 17,
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        columnGap: 5,
        marginTop: 5,
    },
    priceText: {
        color: '#006699',
        fontSize: 12,
        fontWeight: '700',
    },
    addBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#006699',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#006699',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.18,
        shadowRadius: 6,
        elevation: 2,
    },
    addedBtn: {
        backgroundColor: '#64748B',
        shadowColor: '#64748B',
    },

    resultContainer: {
        flex: 1,
        backgroundColor: '#F4F7FA',
        paddingTop: Platform.OS === 'android' ? 54 : 24,
    },
    resultHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 14,
        gap: 12,
    },
    resultSearchBar: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E2E8F0',
        paddingHorizontal: 16,
        height: 46,
        borderRadius: 14,
        gap: 10,
    },
    resultSearchInput: {
        flex: 1,
        fontSize: 15,
        color: '#2d3748',
    },
    resultFiltersContainer: {
        marginBottom: 14,
    },
    resultFilterList: {
        gap: 10,
        paddingHorizontal: 20,
    },
    resultFilterPill: {
        paddingHorizontal: 18,
        paddingVertical: 9,
        borderRadius: 12,
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#CBD5E0',
    },
    resultFilterPillActive: {
        backgroundColor: '#E6F0FA',
        borderColor: '#E6F0FA',
    },
    resultFilterText: {
        fontSize: 14,
        color: '#718096',
        fontWeight: '600',
    },
    resultFilterTextActive: {
        color: '#005f73',
    },
    resultListContainer: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    resultTitleContainer: {
        marginBottom: 18,
    },
    resultMainTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1A202C',
        marginBottom: 4,
    },
    resultSubTitle: {
        fontSize: 14,
        color: '#718096',
    },
    resultCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        marginBottom: 18,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
        overflow: 'hidden',
    },
    resultImageContainer: {
        height: 150,
        width: '100%',
        position: 'relative',
    },
    resultCardImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    resultCategoryBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    resultCategoryBadgeText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#4A5568',
    },
    resultDealBadge: {
        position: 'absolute',
        top: 12,
        right: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#0F6C82',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 999,
    },
    resultDealBadgeText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '800',
    },
    resultCardContent: {
        padding: 14,
    },
    resultCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
        gap: 12,
    },
    resultCardTitle: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2D3748',
    },
    resultRatingPill: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFAF0',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        gap: 4,
    },
    resultRatingText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#D97706',
    },
    resultLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        gap: 4,
    },
    resultLocationText: {
        fontSize: 13,
        color: '#718096',
    },
    resultDescription: {
        fontSize: 13,
        color: '#4A5568',
        lineHeight: 18,
        marginBottom: 16,
    },
    resultCardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    resultReviewsText: {
        fontSize: 12,
        color: '#A0AEC0',
        fontWeight: '500',
    },
    resultAddButton: {
        backgroundColor: '#005f73',
        width: 36,
        height: 36,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#005f73',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    resultAddButtonSelected: {
        backgroundColor: '#A0AEC0',
        shadowColor: '#A0AEC0',
    },
    resultEmptyState: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    resultEmptyTitle: {
        color: '#1A202C',
        fontSize: 16,
        fontWeight: '800',
    },
    resultEmptyText: {
        color: '#718096',
        fontSize: 13,
        marginTop: 4,
    },
});

export default styles;
