import { StyleSheet } from "react-native";
import { getCommonStyles } from "../../common/styles";
import { ThemeType } from "../../common/theme";

const getStyles = (colors: ThemeType) => StyleSheet.create({
    ...getCommonStyles(colors),

    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 40,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingTop: 40,
        paddingHorizontal: 16,
    },
    iconButton: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderRadius: 20,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.primary,
    },
    heroCard: {
        width: '100%',
        height: 140,
        marginBottom: 24,
        justifyContent: 'flex-end',
    },
    heroOverlay: {
        backgroundColor: colors.overlay,
        borderRadius: 16,
        padding: 16,
        height: '100%',
        justifyContent: 'flex-end',
        alignItems: 'flex-start',
    },
    heroSubtitle: {
        color: '#E0E0E0',
        fontSize: 12,
        marginBottom: 4,
    },
    heroTitle: {
        color: colors.white,
        fontSize: 22,
        fontWeight: 'bold',
    },
    changeCoverButton: {
        minHeight: 34,
        borderRadius: 17,
        paddingHorizontal: 12,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        columnGap: 7,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    changeCoverButtonDisabled: {
        opacity: 0.75,
    },
    changeCoverText: {
        color: colors.white,
        fontSize: 13,
        fontWeight: '700',
    },
    section: {
        marginBottom: 24,
    },
    label: {
        fontSize: 13,
        color: colors.textSecondary,
        marginBottom: 6,
        marginTop: 12,
    },
    inputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: colors.border,
    },
    inputIcon: {
        marginRight: 10,
        color: colors.textMuted,
    },
    inputText: {
        fontSize: 15,
        color: colors.textPrimary,
        fontWeight: '500',
    },
    datePickerRow: {
        flexDirection: 'row',
        gap: 10,
    },
    datePickerButton: {
        flex: 1,
        minHeight: 58,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    datePickerLabel: {
        fontSize: 11,
        color: colors.textMuted,
        fontWeight: '700',
        marginBottom: 3,
    },
    durationHint: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '700',
        marginLeft: 12,
        textAlign: 'right',
    },
    scheduleTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 14,
    },
    sectionTitle: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.primary,
        marginBottom: 0,
    },
    itineraryCard: {
        flexDirection: 'row',
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 10,
        marginBottom: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    itineraryImage: {
        width: 84,
        height: 96,
        borderRadius: 10,
        marginRight: 12,
        backgroundColor: colors.surfaceMuted,
    },
    itineraryInfo: {
        flex: 1,
        minWidth: 0,
    },
    itineraryTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        columnGap: 10,
    },
    itineraryTitle: {
        flex: 1,
        fontSize: 15,
        fontWeight: '800',
        color: colors.textPrimary,
    },
    itineraryLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        columnGap: 4,
        marginTop: 4,
    },
    itineraryLocation: {
        flex: 1,
        fontSize: 12,
        color: colors.textSecondary,
        fontWeight: '600',
    },
    itineraryRatingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        columnGap: 4,
        marginTop: 5,
        marginBottom: 8,
    },
    itineraryRatingPill: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 9,
        backgroundColor: colors.surfaceMuted,
        paddingHorizontal: 7,
        paddingVertical: 3,
        columnGap: 3,
        borderWidth: 1,
        borderColor: colors.border,
    },
    itineraryRating: {
        fontSize: 12,
        color: colors.warning,
        fontWeight: '800',
    },
    itineraryDetailsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        columnGap: 8,
        marginTop: 10,
    },
    detailLabel: {
        fontSize: 10,
        color: colors.textMuted,
        marginBottom: 2,
    },
    detailValue: {
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    timeInput: {
        flex: 1,
        minWidth: 0,
        minHeight: 24,
        paddingHorizontal: 0,
        paddingVertical: 2,
        fontSize: 12,
        fontWeight: '800',
        color: colors.primary,
    },
    detailPill: {
        flex: 1,
        minHeight: 34,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 10,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: 9,
        columnGap: 6,
    },
    budgetValue: {
        flex: 1,
        color: colors.success,
        fontSize: 12,
        fontWeight: '800',
    },
    deleteBtn: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 6,
        backgroundColor: colors.dangerSoft,
    },
    addLocationBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        minHeight: 52,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: colors.primary,
        borderStyle: 'dashed',
        borderRadius: 14,
        marginTop: 6,
        backgroundColor: colors.primaryLight,
    },
    addLocationIconWrap: {
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        marginRight: 10,
    },
    addLocationText: {
        flex: 1,
        color: colors.primary,
        fontWeight: 'bold',
        fontSize: 14,
        lineHeight: 19,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    addText: {
        color: colors.primary,
        fontWeight: 'bold',
        fontSize: 14,
    },
    saveButton: {
        minWidth: 82,
        minHeight: 36,
        borderRadius: 18,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        columnGap: 7,
        backgroundColor: colors.primary,
    },
    saveButtonDisabled: {
        opacity: 0.72,
    },
    saveButtonText: {
        color: colors.white,
        fontWeight: '800',
        fontSize: 14,
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    tag: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primaryLight,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 10,
        marginBottom: 10,
    },
    tagText: {
        color: colors.primary,
        marginRight: 6,
        fontSize: 14,
    },
    addTagBtn: {
        backgroundColor: colors.surfaceMuted,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    addTagText: {
        color: colors.textMuted,
        fontSize: 14,
    },
    budgetCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    budgetIconContainer: {
        backgroundColor: colors.primary,
        width: 48,
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    budgetInfo: {
        flex: 1,
    },
    budgetAmount: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    budgetCurrency: {
        fontSize: 13,
        color: colors.textSecondary,
    },
    badge: {
        backgroundColor: colors.primaryLight,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    badgeText: {
        color: colors.primary,
        fontWeight: 'bold',
        fontSize: 12,
    },
    membersRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    avatarsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: colors.surface,
    },
    avatarOverlap: {
        marginLeft: -15,
    },
    avatarExtra: {
        backgroundColor: colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarExtraText: {
        color: colors.primary,
        fontWeight: 'bold',
        fontSize: 14,
    },
    addMemberContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addMemberIconBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'dashed',
    },
    addMemberTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    addMemberSub: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    dayContainer: {
        marginBottom: 18,
        backgroundColor: colors.surface,
        borderRadius: 18,
        padding: 12,
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
    },
    dayHeader: {
        marginBottom: 10,
        paddingHorizontal: 2,
        flexDirection: 'row',
        alignItems: 'center',
    },
    dayTitle: {
        fontSize: 17,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    dayTitleInput: {
        flex: 1,
        minHeight: 40,
        borderRadius: 10,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 17,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
    extraCountContainer: {
        backgroundColor: colors.surfaceMuted,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.surface,
    },
    extraCountText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.textPrimary,
    },
});

export default getStyles;
