import { StyleSheet } from "react-native";
import { commonStyles } from "../common/styles";

const styles = StyleSheet.create({
    ...commonStyles,

    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        marginVertical: 25,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 10,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    iconButton: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1E88E5',
    },
    heroCard: {
        width: '100%',
        height: 140,
        marginBottom: 24,
        justifyContent: 'flex-end',
    },
    heroOverlay: {
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 16,
        padding: 16,
        height: '100%',
        justifyContent: 'flex-end',
    },
    heroSubtitle: {
        color: '#E0E0E0',
        fontSize: 12,
        marginBottom: 4,
    },
    heroTitle: {
        color: '#FFFFFF',
        fontSize: 22,
        fontWeight: 'bold',
    },
    section: {
        marginBottom: 24,
    },
    label: {
        fontSize: 13,
        color: '#666',
        marginBottom: 6,
        marginTop: 12,
    },
    inputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F4F7FB',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    inputIcon: {
        marginRight: 10,
    },
    inputText: {
        fontSize: 15,
        color: '#333',
        fontWeight: '500',
    },
    datePickerRow: {
        flexDirection: 'row',
        gap: 10,
    },
    datePickerButton: {
        flex: 1,
        minHeight: 58,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F4F7FB',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    datePickerLabel: {
        fontSize: 11,
        color: '#888',
        fontWeight: '700',
        marginBottom: 3,
    },
    durationHint: {
        color: '#1E88E5',
        fontSize: 12,
        fontWeight: '700',
        marginLeft: 12,
        textAlign: 'right',
    },
    scheduleTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 14,
    },
    sectionTitle: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1E88E5',
        marginBottom: 0,
    },
    itineraryCard: {
        flexDirection: 'row',
        backgroundColor: '#F4F7FB',
        borderRadius: 14,
        padding: 12,
        marginBottom: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E8EEF6',
    },
    itineraryImage: {
        width: 60,
        height: 60,
        borderRadius: 8,
        marginRight: 12,
    },
    itineraryInfo: {
        flex: 1,
        minWidth: 0,
    },
    itineraryTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#000',
    },
    itineraryRatingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        columnGap: 4,
        marginTop: 3,
        marginBottom: 8,
    },
    itineraryRating: {
        fontSize: 12,
        color: '#888',
        fontWeight: '600',
    },
    itineraryDetailsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        rowGap: 6,
    },
    detailLabel: {
        fontSize: 10,
        color: '#888',
        marginBottom: 2,
    },
    detailValue: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#333',
    },
    deleteBtn: {
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
        backgroundColor: '#FFF1F1',
    },
    addLocationBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        minHeight: 52,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#1E88E5',
        borderStyle: 'dashed',
        borderRadius: 14,
        marginTop: 6,
        backgroundColor: '#F7FBFF',
    },
    addLocationIconWrap: {
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E3F2FD',
        marginRight: 10,
    },
    addLocationText: {
        flex: 1,
        color: '#1E88E5',
        fontWeight: 'bold',
        fontSize: 14,
        lineHeight: 19,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    addText: {
        color: '#1E88E5',
        fontWeight: 'bold',
        fontSize: 14,
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    tag: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E3F2FD',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 10,
        marginBottom: 10,
    },
    tagText: {
        color: '#1E88E5',
        marginRight: 6,
        fontSize: 14,
    },
    addTagBtn: {
        backgroundColor: '#F4F7FB',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 10,
    },
    addTagText: {
        color: '#888',
        fontSize: 14,
    },
    budgetCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F4F7FB',
        borderRadius: 16,
        padding: 16,
    },
    budgetIconContainer: {
        backgroundColor: '#1E88E5',
        width: 48,
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    budgetInfo: {
        flex: 1,
    },
    budgetAmount: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    budgetCurrency: {
        fontSize: 13,
        color: '#888',
    },
    badge: {
        backgroundColor: '#E3F2FD',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    badgeText: {
        color: '#1E88E5',
        fontWeight: 'bold',
        fontSize: 12,
    },
    membersRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    avatarsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#FFF',
    },
    avatarOverlap: {
        marginLeft: -15,
    },
    avatarExtra: {
        backgroundColor: '#E3F2FD',
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarExtraText: {
        color: '#1E88E5',
        fontWeight: 'bold',
        fontSize: 14,
    },
    addMemberContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addMemberIconBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#1E88E5',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'dashed',
    },
    addMemberTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#333',
    },
    addMemberSub: {
        fontSize: 12,
        color: '#888',
    },
    dayContainer: {
        marginBottom: 18,
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        padding: 12,
        borderWidth: 1,
        borderColor: '#EEF3F8',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
    },
    dayHeader: {
        marginBottom: 10,
        paddingHorizontal: 2,
        flexDirection: 'row',
        alignItems: 'center',
    },
    dayTitle: {
        fontSize: 17,
        fontWeight: 'bold',
        color: '#333',
    },
    extraCountContainer: {
        backgroundColor: '#E0E0E0',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    extraCountText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#333333',
    },
});

export default styles;
