import { Platform, StatusBar, StyleSheet } from 'react-native';

export const COLORS = {
    background: '#121418',
    card: 'rgba(22, 24, 28, 0.94)',
    cyan: '#1cb0f6',
    inputBackground: '#1e2329',
    inputText: '#ffffff',
    placeholderText: '#6b7280',
    labelColor: '#9ca3af',
    textColor: '#ffffff',
    mutedText: '#9ca3af',
    borderColor: 'rgba(255,255,255,0.08)',
    buttonText: '#0a1a24',
};

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    container: {
        flex: 1,
    },
    backgroundImage: {
        flex: 1,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 12, 16, 0.72)',
    },
    header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + 16 : 16,
        paddingBottom: 8,
        zIndex: 10,
    },
    backButton: {
        padding: 4,
        marginRight: 12,
    },
    headerTitle: {
        color: COLORS.textColor,
        fontSize: 20,
        fontWeight: '800',
    },
    contentContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 20,
    },
    card: {
        backgroundColor: COLORS.card,
        borderRadius: 28,
        paddingHorizontal: 28,
        paddingVertical: 40,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    iconContainer: {
        alignItems: 'center',
        marginBottom: 24,
    },
    iconBackground: {
        width: 72,
        height: 72,
        backgroundColor: COLORS.inputBackground,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        shadowColor: COLORS.cyan,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 14,
        elevation: 8,
    },
    lockAbsolute: {
        position: 'absolute',
        bottom: 17,
        right: 17,
        backgroundColor: COLORS.inputBackground,
        borderRadius: 8,
        padding: 2,
    },
    title: {
        color: COLORS.textColor,
        fontSize: 30,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 14,
    },
    subtitle: {
        color: COLORS.mutedText,
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 23,
        marginBottom: 34,
    },
    formContainer: {
        gap: 22,
    },
    inputGroup: {
        gap: 10,
    },
    label: {
        color: COLORS.labelColor,
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.2,
        marginLeft: 4,
    },
    input: {
        height: 54,
        backgroundColor: COLORS.inputBackground,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        borderRadius: 16,
        color: COLORS.inputText,
        paddingHorizontal: 18,
        fontSize: 16,
    },
    submitButton: {
        backgroundColor: COLORS.cyan,
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 17,
        gap: 10,
        shadowColor: COLORS.cyan,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 8,
    },
    submitText: {
        color: COLORS.buttonText,
        fontSize: 17,
        fontWeight: '800',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'center',
        flexWrap: 'wrap',
        marginTop: 30,
    },
    footerText: {
        color: COLORS.mutedText,
        fontSize: 15,
    },
    loginText: {
        color: COLORS.cyan,
        fontSize: 15,
        fontWeight: '700',
    },
});

export default styles;
