import { StyleSheet } from 'react-native';
import { commonStyles } from '../common/styles';

const styles = StyleSheet.create({
  ...commonStyles,

  container: { flex: 1, backgroundColor: '#f8fafc' },
  headerContainer: { paddingHorizontal: 20, paddingTop: 35, backgroundColor: '#fff', paddingBottom: 10 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  headerTitle: { fontSize: 25, fontWeight: 'bold', color: '#1e293b', flex: 1 },
  addButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0f6c82',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, position: 'relative' },
  searchIcon: { position: 'absolute', left: 15, zIndex: 1 },
  clearIcon: { position: 'absolute', right: 15, zIndex: 1 },
  searchInput: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    borderRadius: 25,
    paddingLeft: 45,
    paddingRight: 45,
    height: 45,
    color: '#333',
  },
  filtersScroll: { flexDirection: 'row' },
  filterChip: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginRight: 10,
  },
  filterChipActive: { backgroundColor: '#0f6c82', borderColor: '#0f6c82' },
  filterText: { color: '#64748b', fontSize: 14, fontWeight: '600' },
  filterTextActive: { color: '#fff' },
  listContainer: { flex: 1 },
  listContent: { padding: 20, paddingBottom: 100 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    marginBottom: 20,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#fff',
  },
  imageContainer: { height: 180, width: '100%', position: 'relative' },
  cardImage: { width: '100%', height: '100%' },
  categoryBadge: {
    position: 'absolute',
    top: 15,
    left: 15,
    backgroundColor: 'rgba(15,108,130,0.9)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  categoryText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  cardBody: { padding: 15, flexDirection: 'row', justifyContent: 'space-between'},
  cardText: { flexDirection: 'column', rowGap: 2, justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 5 },
  cardTitle: { fontSize: 16, fontWeight: 'bold', color: '#1e293b', flex: 1, marginRight: 10 },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff7ed',
    paddingHorizontal: 5,
    paddingVertical: 0,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffedd5',
  },
  ratingText: { fontSize: 14, fontWeight: 'bold', color: '#c2410c', marginLeft: 5 },
  locationRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  locationInfo: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 12 },
  locationText: { fontSize: 13, color: '#64748b', marginLeft: 4, flex: 1 },
  emptyStateContainer: { alignItems: 'center', justifyContent: 'center', marginTop: 50 },
  emptyStateText: { marginTop: 10, color: '#94a3b8', fontSize: 14, fontWeight: '500' },

});

export default styles;
