import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#f8fafc' },
    container: { flex: 1, backgroundColor: '#f8fafc' },
    contentArea: { flex: 1, paddingHorizontal: 16 },
    scrollContent: { paddingBottom: 120 },

    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 38,
        paddingBottom: 12,
    },
    headerEyebrow: { fontSize: 12, fontWeight: '700', color: '#0284c7', marginBottom: 3 },
    headerTitle: { fontSize: 22, fontWeight: '900', color: '#0f172a' },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 13,
        paddingVertical: 9,
        borderRadius: 12,
        backgroundColor: '#fff1f2',
        borderWidth: 1,
        borderColor: '#fecdd3',
    },
    logoutText: { fontSize: 12, fontWeight: '800', color: '#dc2626' },

    summaryCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    summaryLabel: { fontSize: 12, fontWeight: '800', color: '#64748b', textTransform: 'uppercase' },
    summaryValue: { marginTop: 5, fontSize: 20, fontWeight: '900', color: '#0f172a' },
    summaryIconWrap: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: '#e0f2fe',
        justifyContent: 'center',
        alignItems: 'center',
    },
    summaryIconWrapDanger: { backgroundColor: '#fee2e2' },

    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        paddingHorizontal: 16,
        height: 50,
        borderRadius: 14,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    searchIcon: { marginRight: 8 },
    searchInput: { flex: 1, fontSize: 14, color: '#0f172a' },

    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#e2e8f0',
        borderRadius: 14,
        padding: 4,
        marginBottom: 14,
    },
    tabButton: {
        flex: 1,
        minHeight: 42,
        paddingVertical: 9,
        paddingHorizontal: 6,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    tabButtonActive: { backgroundColor: '#ffffff' },
    tabText: { fontSize: 13, fontWeight: '700', color: '#64748b', textAlign: 'center' },
    tabTextActive: { color: '#0369a1', fontWeight: '900' },

    loadingState: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    loadingText: { marginTop: 12, color: '#64748b', fontWeight: '600' },
    cardList: { gap: 12 },

    userCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 14,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        elevation: 2,
    },
    userCardBanned: { borderColor: '#fecaca', backgroundColor: '#fffafa' },
    cardTopRow: { flexDirection: 'row', alignItems: 'center' },
    avatar: { width: 52, height: 52, borderRadius: 16, marginRight: 12, backgroundColor: '#e2e8f0' },
    avatarBanned: { opacity: 0.55 },
    userMainInfo: { flex: 1, minWidth: 0 },
    nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    userName: { flex: 1, fontSize: 16, fontWeight: '900', color: '#0f172a' },
    textBanned: { color: '#94a3b8', textDecorationLine: 'line-through' },
    userEmail: { marginTop: 4, fontSize: 13, color: '#475569' },
    userJoined: { marginTop: 3, fontSize: 11, color: '#94a3b8', fontWeight: '600' },

    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: '#dcfce7',
    },
    statusBadgeBanned: { backgroundColor: '#fee2e2' },
    statusBadgeText: { fontSize: 10, fontWeight: '900', color: '#16a34a' },
    statusBadgeTextBanned: { color: '#dc2626' },

    metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 14 },
    metricPill: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 10,
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    metricValue: { fontSize: 15, fontWeight: '900', color: '#0f172a' },
    metricLabel: { marginTop: 1, fontSize: 10, fontWeight: '700', color: '#64748b' },
    roleBadge: {
        minHeight: 42,
        paddingHorizontal: 12,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, alignSelf: 'flex-start' },
    badgeText: { fontSize: 10, fontWeight: '900' },

    statusBtn: {
        marginTop: 14,
        minHeight: 44,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 7,
    },
    btnBan: { backgroundColor: '#dc2626' },
    btnBanText: { fontSize: 14, fontWeight: '900', color: '#ffffff' },
    btnActive: { backgroundColor: '#dcfce7', borderWidth: 1, borderColor: '#86efac' },
    btnActiveText: { fontSize: 14, fontWeight: '900', color: '#166534' },

    emptyState: {
        alignItems: 'center',
        paddingVertical: 34,
        paddingHorizontal: 20,
        backgroundColor: '#ffffff',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    emptyTitle: { marginTop: 10, fontSize: 16, fontWeight: '900', color: '#334155' },
    emptyText: { marginTop: 5, textAlign: 'center', color: '#94a3b8', lineHeight: 19 },

    paginationRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 4,
        paddingBottom: 10,
        gap: 10,
    },
    paginationText: { fontSize: 12, color: '#64748b', flex: 1, fontWeight: '600' },
    paginationControls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    pageArrowBtn: {
        width: 34,
        height: 34,
        borderRadius: 17,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    pageIndicator: { fontSize: 12, fontWeight: '900', color: '#334155' },

    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 22,
        width: '100%',
        maxWidth: 400,
    },
    modalTitle: { fontSize: 18, fontWeight: '900', color: '#0f172a', marginBottom: 8 },
    modalBody: { fontSize: 14, color: '#64748b', marginBottom: 16 },
    roleOptions: { gap: 8, marginBottom: 16 },
    roleOption: {
        borderWidth: 2,
        borderColor: '#e2e8f0',
        borderRadius: 12,
        padding: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    roleOptionActive: { borderColor: '#0284c7', backgroundColor: '#f0f9ff' },
    roleOptionText: { fontSize: 15, fontWeight: '800', color: '#0f172a' },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
    modalCancelButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: '#f1f5f9',
    },
    modalCancelText: { fontSize: 14, fontWeight: '800', color: '#475569' },
    modalPrimaryButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: '#0284c7',
    },
    modalPrimaryText: { fontSize: 14, fontWeight: '800', color: '#ffffff' },
});
