import { Platform, StatusBar, StyleSheet } from 'react-native';

export const COLORS = {
    background: '#121418',
    card: 'rgba(22, 24, 28, 0.94)',
    cyan: '#1cb0f6',
    inputBackground: '#1e2329',
    textColor: '#ffffff',
    mutedText: '#9ca3af',
    borderColor: 'rgba(255,255,255,0.08)',
    buttonText: '#0a1a24',
};

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    backgroundImage: {
        flex: 1,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 12, 16, 0.72)',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + 16 : 16,
        paddingBottom: 12,
        zIndex: 10,
    },
    backButton: {
        padding: 4,
        marginRight: 12,
    },
    headerTitle: {
        color: COLORS.textColor,
        fontSize: 20,
        fontWeight: '800',
    },
    container: {
        flex: 1,
    },
    contentContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    card: {
        backgroundColor: COLORS.card,
        borderRadius: 28,
        paddingHorizontal: 24,
        paddingVertical: 40,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    iconContainer: {
        alignItems: 'center',
        marginBottom: 24,
    },
    iconBackground: {
        width: 72,
        height: 72,
        backgroundColor: COLORS.cyan,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.cyan,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.45,
        shadowRadius: 16,
        elevation: 8,
    },
    lockAbsolute: {
        position: 'absolute',
        bottom: 17,
        right: 17,
        backgroundColor: '#ffffff',
        borderRadius: 8,
        padding: 2,
    },
    title: {
        color: COLORS.textColor,
        fontSize: 30,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 14,
    },
    subtitle: {
        color: COLORS.mutedText,
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 23,
        marginBottom: 34,
    },
    emailHighlight: {
        color: COLORS.cyan,
        fontWeight: '700',
    },
    otpContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 34,
        gap: 8,
    },
    otpBox: {
        flex: 1,
        height: 56,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        backgroundColor: COLORS.inputBackground,
        justifyContent: 'center',
        alignItems: 'center',
    },
    otpBoxActive: {
        borderColor: COLORS.cyan,
        backgroundColor: 'rgba(28, 176, 246, 0.08)',
    },
    otpBoxFilled: {
        borderColor: 'rgba(255,255,255,0.22)',
    },
    otpText: {
        color: COLORS.textColor,
        fontSize: 24,
        fontWeight: '800',
    },
    hiddenInput: {
        position: 'absolute',
        width: 1,
        height: 1,
        opacity: 0,
    },
    submitButton: {
        backgroundColor: COLORS.cyan,
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 17,
        gap: 10,
        shadowColor: COLORS.cyan,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 8,
    },
    submitText: {
        color: COLORS.buttonText,
        fontSize: 17,
        fontWeight: '800',
    },
    footer: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 30,
        gap: 8,
    },
    footerText: {
        color: COLORS.mutedText,
        fontSize: 14,
    },
    resendText: {
        color: COLORS.cyan,
        fontSize: 15,
        fontWeight: '700',
    },
});
