import { Platform, StatusBar, StyleSheet } from 'react-native';

export const COLORS = {
    background: '#121418',
    card: 'rgba(22, 24, 28, 0.95)',
    cyan: '#1cb0f6',
    inputBackground: '#1e2329',
    inputText: '#ffffff',
    placeholderText: '#6b7280',
    labelColor: '#9ca3af',
    textColor: '#ffffff',
    mutedText: '#9ca3af',
    borderColor: 'rgba(255,255,255,0.08)',
};

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    backgroundImage: {
        flex: 1,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 12, 16, 0.7)',
    },
    header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + 16 : 16,
        paddingBottom: 8,
        zIndex: 10,
    },
    backButton: {
        padding: 4,
        marginRight: 12,
    },
    headerTitle: {
        color: COLORS.textColor,
        fontSize: 20,
        fontWeight: 'bold',
    },
    container: {
        flex: 1,
    },
    contentContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 20,
    },
    card: {
        backgroundColor: COLORS.card,
        borderRadius: 32,
        paddingHorizontal: 28,
        paddingVertical: 44,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
    },
    iconContainer: {
        alignItems: 'center',
        marginBottom: 32,
    },
    iconBackground: {
        width: 76,
        height: 76,
        backgroundColor: COLORS.cyan,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.cyan,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 15,
        elevation: 10,
    },
    title: {
        color: COLORS.textColor,
        fontSize: 30,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 16,
    },
    subtitle: {
        color: COLORS.mutedText,
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 40,
    },
    formContainer: {
        gap: 22,
    },
    inputGroup: {
        gap: 10,
    },
    label: {
        color: COLORS.labelColor,
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.2,
        marginLeft: 4,
    },
    passwordWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        height: 54,
        backgroundColor: COLORS.inputBackground,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.borderColor,
        paddingLeft: 18,
    },
    input: {
        flex: 1,
        color: COLORS.inputText,
        paddingVertical: 0,
        fontSize: 16,
    },
    eyeIcon: {
        alignSelf: 'stretch',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 18,
    },
    requirementsContainer: {
        marginTop: 8,
        marginBottom: 8,
        gap: 12,
    },
    requirementsTitle: {
        color: COLORS.textColor,
        fontSize: 15,
        fontWeight: '600',
        marginBottom: 6,
    },
    requirementRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    requirementText: {
        color: COLORS.mutedText,
        fontSize: 14,
    },
    submitButton: {
        backgroundColor: COLORS.cyan,
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 20,
        marginTop: 16,
        gap: 10,
        shadowColor: COLORS.cyan,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    },
    submitText: {
        color: '#0a1a24',
        fontSize: 18,
        fontWeight: 'bold',
    },
    footerLink: {
        alignItems: 'center',
        marginTop: 12,
    },
    footerLinkText: {
        color: COLORS.cyan,
        fontSize: 15,
        fontWeight: '700',
    },
});
